
// Objective-C API for talking to the following Go packages
//
//	crim_sdk/crim_sdk
//	crim_sdk/crim_sdk_callback
//
// File is generated by gomobile bind. Do not edit.
#ifndef __CRIMSDKCore_FRAMEWORK_H__
#define __CRIMSDKCore_FRAMEWORK_H__

#include "Crim_sdk.objc.h"
#include "Crim_sdk_callback.objc.h"
#include "Universe.objc.h"

#endif
