// Objective-C API for talking to crim_sdk/crim_sdk_callback Go package.
//   gobind -lang=objc crim_sdk/crim_sdk_callback
//
// File is generated by gobind. Do not edit.

#ifndef __Crim_sdk_callback_H__
#define __Crim_sdk_callback_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Crim_sdk_callbackBase;
@class Crim_sdk_callbackBase;
@protocol Crim_sdk_callbackOnAdvancedMsgListener;
@class Crim_sdk_callbackOnAdvancedMsgListener;
@protocol Crim_sdk_callbackOnBatchMsgListener;
@class Crim_sdk_callbackOnBatchMsgListener;
@protocol Crim_sdk_callbackOnConnListener;
@class Crim_sdk_callbackOnConnListener;
@protocol Crim_sdk_callbackOnConversationListener;
@class Crim_sdk_callbackOnConversationListener;
@protocol Crim_sdk_callbackOnCustomBusinessListener;
@class Crim_sdk_callbackOnCustomBusinessListener;
@protocol Crim_sdk_callbackOnFriendshipListener;
@class Crim_sdk_callbackOnFriendshipListener;
@protocol Crim_sdk_callbackOnFriendshipListenerSdk;
@class Crim_sdk_callbackOnFriendshipListenerSdk;
@protocol Crim_sdk_callbackOnGrpListener;
@class Crim_sdk_callbackOnGrpListener;
@protocol Crim_sdk_callbackOnListenerForService;
@class Crim_sdk_callbackOnListenerForService;
@protocol Crim_sdk_callbackOnMsgKvInfoListener;
@class Crim_sdk_callbackOnMsgKvInfoListener;
@protocol Crim_sdk_callbackOnSignalingListener;
@class Crim_sdk_callbackOnSignalingListener;
@protocol Crim_sdk_callbackOnUserListener;
@class Crim_sdk_callbackOnUserListener;
@protocol Crim_sdk_callbackSendMsgCallBack;
@class Crim_sdk_callbackSendMsgCallBack;
@protocol Crim_sdk_callbackUploadFileCallback;
@class Crim_sdk_callbackUploadFileCallback;

@protocol Crim_sdk_callbackBase <NSObject>
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@protocol Crim_sdk_callbackOnAdvancedMsgListener <NSObject>
- (void)onMsgDeleted:(NSString* _Nullable)message;
- (void)onNewRecvMsgRevoked:(NSString* _Nullable)messageRevoked;
- (void)onRecv1v1ReadReceipt:(NSString* _Nullable)msgReceiptList;
- (void)onRecvGrpReadReceipt:(NSString* _Nullable)groupMsgReceiptList;
- (void)onRecvMsgExtensionsAdded:(NSString* _Nullable)msgID reactionExtensionList:(NSString* _Nullable)reactionExtensionList;
- (void)onRecvMsgExtensionsChanged:(NSString* _Nullable)msgID reactionExtensionList:(NSString* _Nullable)reactionExtensionList;
- (void)onRecvMsgExtensionsDeleted:(NSString* _Nullable)msgID reactionExtensionKeyList:(NSString* _Nullable)reactionExtensionKeyList;
- (void)onRecvNewMsg:(NSString* _Nullable)message;
- (void)onRecvOfflineNewMsg:(NSString* _Nullable)message;
@end

@protocol Crim_sdk_callbackOnBatchMsgListener <NSObject>
- (void)onRecvNewMsgs:(NSString* _Nullable)messageList;
- (void)onRecvOfflineNewMsgs:(NSString* _Nullable)messageList;
@end

@protocol Crim_sdk_callbackOnConnListener <NSObject>
- (void)onConnectFailed:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onConnectSuccess;
- (void)onConnecting;
- (void)onKickedOffline;
- (void)onUserTokenExpired;
@end

@protocol Crim_sdk_callbackOnConversationListener <NSObject>
- (void)onConversationChanged:(NSString* _Nullable)conversationList;
- (void)onNewConversation:(NSString* _Nullable)conversationList;
/**
 * OnSyncServerProgress(progress int)
 */
- (void)onSyncServerFailed;
- (void)onSyncServerFinish;
- (void)onSyncServerStart;
- (void)onTotalUnreadMsgCountChanged:(int32_t)totalUnreadCount;
@end

@protocol Crim_sdk_callbackOnCustomBusinessListener <NSObject>
- (void)onRecvCustomBusinessMsg:(NSString* _Nullable)businessMessage;
@end

@protocol Crim_sdk_callbackOnFriendshipListener <NSObject>
- (void)onBlackAdded:(NSString* _Nullable)blackInfo;
- (void)onBlackDeleted:(NSString* _Nullable)blackInfo;
- (void)onFriendAdded:(NSString* _Nullable)friendInfo;
- (void)onFriendDeleted:(NSString* _Nullable)friendInfo;
- (void)onFriendInfoChanged:(NSString* _Nullable)friendInfo;
- (void)onFriendReqAccepted:(NSString* _Nullable)friendApplication;
- (void)onFriendReqAdded:(NSString* _Nullable)friendApplication;
- (void)onFriendReqDeleted:(NSString* _Nullable)friendApplication;
- (void)onFriendReqRejected:(NSString* _Nullable)friendApplication;
@end

@protocol Crim_sdk_callbackOnFriendshipListenerSdk <NSObject>
// skipped method OnFriendshipListenerSdk.OnBlackAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnBlackDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationAccepted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationRejected with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendInfoChanged with unsupported parameter or return types

@end

@protocol Crim_sdk_callbackOnGrpListener <NSObject>
- (void)onGrpDismissed:(NSString* _Nullable)groupInfo;
- (void)onGrpInfoChanged:(NSString* _Nullable)groupInfo;
- (void)onGrpMemberAdded:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpMemberDeleted:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpMemberInfoChanged:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpReqAccepted:(NSString* _Nullable)groupApplication;
- (void)onGrpReqAdded:(NSString* _Nullable)groupApplication;
- (void)onGrpReqDeleted:(NSString* _Nullable)groupApplication;
- (void)onGrpReqRejected:(NSString* _Nullable)groupApplication;
- (void)onJoinedGrpAdded:(NSString* _Nullable)groupInfo;
- (void)onJoinedGrpDeleted:(NSString* _Nullable)groupInfo;
@end

@protocol Crim_sdk_callbackOnListenerForService <NSObject>
/**
 * 好友申请被同意
 */
- (void)onFriendReqAccepted:(NSString* _Nullable)groupApplication;
/**
 * 有人申请添加你为好友
 */
- (void)onFriendReqAdded:(NSString* _Nullable)friendApplication;
/**
 * 进群申请被同意
 */
- (void)onGrpReqAccepted:(NSString* _Nullable)groupApplication;
/**
 * 有人申请进群
 */
- (void)onGrpReqAdded:(NSString* _Nullable)groupApplication;
/**
 * 收到新消息
 */
- (void)onRecvNewMsg:(NSString* _Nullable)message;
@end

@protocol Crim_sdk_callbackOnMsgKvInfoListener <NSObject>
- (void)onMsgKvInfoChanged:(NSString* _Nullable)messageChangedList;
@end

@protocol Crim_sdk_callbackOnSignalingListener <NSObject>
- (void)onHangUp:(NSString* _Nullable)hangUpCallback;
- (void)onInvitationCancelled:(NSString* _Nullable)invitationCancelledCallback;
- (void)onInvitationTimeout:(NSString* _Nullable)invitationTimeoutCallback;
- (void)onInviteeAccepted:(NSString* _Nullable)inviteeAcceptedCallback;
- (void)onInviteeAcceptedByOtherDevice:(NSString* _Nullable)inviteeAcceptedCallback;
- (void)onInviteeRejected:(NSString* _Nullable)inviteeRejectedCallback;
- (void)onInviteeRejectedByOtherDevice:(NSString* _Nullable)inviteeRejectedCallback;
- (void)onReceiveNewInvitation:(NSString* _Nullable)receiveNewInvitationCallback;
- (void)onRoomParticipantConnected:(NSString* _Nullable)onRoomParticipantConnectedCallback;
- (void)onRoomParticipantDisconnected:(NSString* _Nullable)onRoomParticipantDisconnectedCallback;
@end

@protocol Crim_sdk_callbackOnUserListener <NSObject>
- (void)onSelfInfoUpdated:(NSString* _Nullable)userInfo;
@end

@protocol Crim_sdk_callbackSendMsgCallBack <NSObject>
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onProgress:(long)progress;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@protocol Crim_sdk_callbackUploadFileCallback <NSObject>
- (void)complete:(int64_t)size url:(NSString* _Nullable)url typ:(long)typ;
- (void)hashPartComplete:(NSString* _Nullable)partsHash fileHash:(NSString* _Nullable)fileHash;
- (void)hashPartProgress:(long)index size:(int64_t)size partHash:(NSString* _Nullable)partHash;
- (void)open:(int64_t)size;
- (void)partSize:(int64_t)partSize num:(long)num;
- (void)uploadComplete:(int64_t)fileSize streamSize:(int64_t)streamSize storageSize:(int64_t)storageSize;
- (void)uploadID:(NSString* _Nullable)uploadID;
- (void)uploadPartComplete:(long)index partSize:(int64_t)partSize partHash:(NSString* _Nullable)partHash;
@end

FOUNDATION_EXPORT id<Crim_sdk_callbackOnFriendshipListenerSdk> _Nullable Crim_sdk_callbackNewOnFriendshipListenerSdk(id<Crim_sdk_callbackOnFriendshipListener> _Nullable listener);

@class Crim_sdk_callbackBase;

@class Crim_sdk_callbackOnAdvancedMsgListener;

@class Crim_sdk_callbackOnBatchMsgListener;

@class Crim_sdk_callbackOnConnListener;

@class Crim_sdk_callbackOnConversationListener;

@class Crim_sdk_callbackOnCustomBusinessListener;

@class Crim_sdk_callbackOnFriendshipListener;

@class Crim_sdk_callbackOnFriendshipListenerSdk;

@class Crim_sdk_callbackOnGrpListener;

@class Crim_sdk_callbackOnListenerForService;

@class Crim_sdk_callbackOnMsgKvInfoListener;

@class Crim_sdk_callbackOnSignalingListener;

@class Crim_sdk_callbackOnUserListener;

@class Crim_sdk_callbackSendMsgCallBack;

@class Crim_sdk_callbackUploadFileCallback;

@interface Crim_sdk_callbackBase : NSObject <goSeqRefInterface, Crim_sdk_callbackBase> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@interface Crim_sdk_callbackOnAdvancedMsgListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnAdvancedMsgListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onMsgDeleted:(NSString* _Nullable)message;
- (void)onNewRecvMsgRevoked:(NSString* _Nullable)messageRevoked;
- (void)onRecv1v1ReadReceipt:(NSString* _Nullable)msgReceiptList;
- (void)onRecvGrpReadReceipt:(NSString* _Nullable)groupMsgReceiptList;
- (void)onRecvMsgExtensionsAdded:(NSString* _Nullable)msgID reactionExtensionList:(NSString* _Nullable)reactionExtensionList;
- (void)onRecvMsgExtensionsChanged:(NSString* _Nullable)msgID reactionExtensionList:(NSString* _Nullable)reactionExtensionList;
- (void)onRecvMsgExtensionsDeleted:(NSString* _Nullable)msgID reactionExtensionKeyList:(NSString* _Nullable)reactionExtensionKeyList;
- (void)onRecvNewMsg:(NSString* _Nullable)message;
- (void)onRecvOfflineNewMsg:(NSString* _Nullable)message;
@end

@interface Crim_sdk_callbackOnBatchMsgListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnBatchMsgListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onRecvNewMsgs:(NSString* _Nullable)messageList;
- (void)onRecvOfflineNewMsgs:(NSString* _Nullable)messageList;
@end

@interface Crim_sdk_callbackOnConnListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnConnListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onConnectFailed:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onConnectSuccess;
- (void)onConnecting;
- (void)onKickedOffline;
- (void)onUserTokenExpired;
@end

@interface Crim_sdk_callbackOnConversationListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnConversationListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onConversationChanged:(NSString* _Nullable)conversationList;
- (void)onNewConversation:(NSString* _Nullable)conversationList;
/**
 * OnSyncServerProgress(progress int)
 */
- (void)onSyncServerFailed;
- (void)onSyncServerFinish;
- (void)onSyncServerStart;
- (void)onTotalUnreadMsgCountChanged:(int32_t)totalUnreadCount;
@end

@interface Crim_sdk_callbackOnCustomBusinessListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnCustomBusinessListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onRecvCustomBusinessMsg:(NSString* _Nullable)businessMessage;
@end

@interface Crim_sdk_callbackOnFriendshipListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnFriendshipListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onBlackAdded:(NSString* _Nullable)blackInfo;
- (void)onBlackDeleted:(NSString* _Nullable)blackInfo;
- (void)onFriendAdded:(NSString* _Nullable)friendInfo;
- (void)onFriendDeleted:(NSString* _Nullable)friendInfo;
- (void)onFriendInfoChanged:(NSString* _Nullable)friendInfo;
- (void)onFriendReqAccepted:(NSString* _Nullable)friendApplication;
- (void)onFriendReqAdded:(NSString* _Nullable)friendApplication;
- (void)onFriendReqDeleted:(NSString* _Nullable)friendApplication;
- (void)onFriendReqRejected:(NSString* _Nullable)friendApplication;
@end

@interface Crim_sdk_callbackOnFriendshipListenerSdk : NSObject <goSeqRefInterface, Crim_sdk_callbackOnFriendshipListenerSdk> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped method OnFriendshipListenerSdk.OnBlackAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnBlackDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationAccepted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationAdded with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendApplicationRejected with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendDeleted with unsupported parameter or return types

// skipped method OnFriendshipListenerSdk.OnFriendInfoChanged with unsupported parameter or return types

@end

@interface Crim_sdk_callbackOnGrpListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnGrpListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onGrpDismissed:(NSString* _Nullable)groupInfo;
- (void)onGrpInfoChanged:(NSString* _Nullable)groupInfo;
- (void)onGrpMemberAdded:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpMemberDeleted:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpMemberInfoChanged:(NSString* _Nullable)groupMemberInfo;
- (void)onGrpReqAccepted:(NSString* _Nullable)groupApplication;
- (void)onGrpReqAdded:(NSString* _Nullable)groupApplication;
- (void)onGrpReqDeleted:(NSString* _Nullable)groupApplication;
- (void)onGrpReqRejected:(NSString* _Nullable)groupApplication;
- (void)onJoinedGrpAdded:(NSString* _Nullable)groupInfo;
- (void)onJoinedGrpDeleted:(NSString* _Nullable)groupInfo;
@end

@interface Crim_sdk_callbackOnListenerForService : NSObject <goSeqRefInterface, Crim_sdk_callbackOnListenerForService> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * 好友申请被同意
 */
- (void)onFriendReqAccepted:(NSString* _Nullable)groupApplication;
/**
 * 有人申请添加你为好友
 */
- (void)onFriendReqAdded:(NSString* _Nullable)friendApplication;
/**
 * 进群申请被同意
 */
- (void)onGrpReqAccepted:(NSString* _Nullable)groupApplication;
/**
 * 有人申请进群
 */
- (void)onGrpReqAdded:(NSString* _Nullable)groupApplication;
/**
 * 收到新消息
 */
- (void)onRecvNewMsg:(NSString* _Nullable)message;
@end

@interface Crim_sdk_callbackOnMsgKvInfoListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnMsgKvInfoListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onMsgKvInfoChanged:(NSString* _Nullable)messageChangedList;
@end

@interface Crim_sdk_callbackOnSignalingListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnSignalingListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onHangUp:(NSString* _Nullable)hangUpCallback;
- (void)onInvitationCancelled:(NSString* _Nullable)invitationCancelledCallback;
- (void)onInvitationTimeout:(NSString* _Nullable)invitationTimeoutCallback;
- (void)onInviteeAccepted:(NSString* _Nullable)inviteeAcceptedCallback;
- (void)onInviteeAcceptedByOtherDevice:(NSString* _Nullable)inviteeAcceptedCallback;
- (void)onInviteeRejected:(NSString* _Nullable)inviteeRejectedCallback;
- (void)onInviteeRejectedByOtherDevice:(NSString* _Nullable)inviteeRejectedCallback;
- (void)onReceiveNewInvitation:(NSString* _Nullable)receiveNewInvitationCallback;
- (void)onRoomParticipantConnected:(NSString* _Nullable)onRoomParticipantConnectedCallback;
- (void)onRoomParticipantDisconnected:(NSString* _Nullable)onRoomParticipantDisconnectedCallback;
@end

@interface Crim_sdk_callbackOnUserListener : NSObject <goSeqRefInterface, Crim_sdk_callbackOnUserListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onSelfInfoUpdated:(NSString* _Nullable)userInfo;
@end

@interface Crim_sdk_callbackSendMsgCallBack : NSObject <goSeqRefInterface, Crim_sdk_callbackSendMsgCallBack> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onProgress:(long)progress;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@interface Crim_sdk_callbackUploadFileCallback : NSObject <goSeqRefInterface, Crim_sdk_callbackUploadFileCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)complete:(int64_t)size url:(NSString* _Nullable)url typ:(long)typ;
- (void)hashPartComplete:(NSString* _Nullable)partsHash fileHash:(NSString* _Nullable)fileHash;
- (void)hashPartProgress:(long)index size:(int64_t)size partHash:(NSString* _Nullable)partHash;
- (void)open:(int64_t)size;
- (void)partSize:(int64_t)partSize num:(long)num;
- (void)uploadComplete:(int64_t)fileSize streamSize:(int64_t)streamSize storageSize:(int64_t)storageSize;
- (void)uploadID:(NSString* _Nullable)uploadID;
- (void)uploadPartComplete:(long)index partSize:(int64_t)partSize partHash:(NSString* _Nullable)partHash;
@end

#endif
